---
name: "КиноПоиск"
guid: "0c136f8a-ff77-4f2b-ade5-13462cae6216"
imageUrl: "https://kinopoisk.userecho.com/s/attachments/28876/0/1/25f8c0315e6ccb2aa6c2642e48f2c9e9.png"
version: "10.7.0.4"
targetAbi: "10.7.0"
framework: "net5.0"
owner: "linfor"
overview: "Загружает рейтинги сайта КиноПоиск"
description: >
  Загружает рейтинги сайта КиноПоиск
category: "Metadata"
artifacts:
- "Jellyfin.Plugin.Kinopoisk.dll"
- "Macross.Json.Extensions.dll"
changelog: >
  Don't provide empty poster
  Added kinopoisk hyperlink in people info
